/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DiscoHyperlink {
        "inUse": boolean;
        "peepConnections": number;
    }
    interface DiscoRoom {
        "host": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface DiscoHyperlinkCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDiscoHyperlinkElement;
}
declare global {
    interface HTMLDiscoHyperlinkElement extends Components.DiscoHyperlink, HTMLStencilElement {
    }
    var HTMLDiscoHyperlinkElement: {
        prototype: HTMLDiscoHyperlinkElement;
        new (): HTMLDiscoHyperlinkElement;
    };
    interface HTMLDiscoRoomElement extends Components.DiscoRoom, HTMLStencilElement {
    }
    var HTMLDiscoRoomElement: {
        prototype: HTMLDiscoRoomElement;
        new (): HTMLDiscoRoomElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "disco-hyperlink": HTMLDiscoHyperlinkElement;
        "disco-room": HTMLDiscoRoomElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DiscoHyperlink {
        "inUse"?: boolean;
        "onDiscoHyperlinkClick"?: (event: DiscoHyperlinkCustomEvent<string>) => void;
        "peepConnections"?: number;
    }
    interface DiscoRoom {
        "host"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "disco-hyperlink": DiscoHyperlink;
        "disco-room": DiscoRoom;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "disco-hyperlink": LocalJSX.DiscoHyperlink & JSXBase.HTMLAttributes<HTMLDiscoHyperlinkElement>;
            "disco-room": LocalJSX.DiscoRoom & JSXBase.HTMLAttributes<HTMLDiscoRoomElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
